# In this notebook, we will learn the basics of TensorFlow.


In [1]:
import tensorflow as tf
print(tf.__version__)

2.10.0


## 创建一个Tensor

In [12]:
string = tf.Variable("This is a string", tf.string)
number = tf.Variable([3,2,4], tf.int16)
floating = tf.Variable(3.567, tf.float64)

print(number)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([3, 2, 4])>


In [3]:
rank1 = tf.Variable(["Test", "OK", "Pydoge"], tf.string)
rank2 = tf.Variable([["OK", "Pydoge"], ["Test", "Go"]], tf.string)

In [4]:
tf.rank(rank1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [5]:
tf.rank(rank2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [6]:
rank1.shape

TensorShape([3])

In [7]:
rank2.shape

TensorShape([2, 2])

## 改变Tensor的形状

In [8]:
tensor1 = tf.ones([1,2,3])

In [9]:
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3,2,1])

In [10]:
print(tensor1)
print(tensor2)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
