# In this notebook, we will learn the basics of TensorFlow.


In [18]:
import tensorflow as tf
print(tf.__version__)

2.10.0


## 创建一个Tensor

In [19]:
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)


In [20]:
rank1 = tf.Variable(["Test", "OK", "Pydoge"], tf.string)
rank2 = tf.Variable([["OK", "Pydoge"], ["Test", "Go"]], tf.string)

In [21]:
tf.rank(rank1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [22]:
tf.rank(rank2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [23]:
rank1.shape

TensorShape([3])

In [24]:
rank2.shape

TensorShape([2, 2])

## 改变Tensor的形状

In [25]:
tensor1 = tf.ones([1,2,3])

In [26]:
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3,2,1])

In [27]:
print(tensor1)
print(tensor2)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
