# 张量的基础

In [36]:
import tensorflow as tf
import numpy as np

# 创建0维张量
scaler = tf.constant(5)
print("标量", scaler)
print("标量的形状", scaler.shape)
print("标量的值", scaler.numpy())

标量 tf.Tensor(5, shape=(), dtype=int32)
标量的形状 ()
标量的值 5


In [37]:
# 创建一维向量
vector = tf.constant([1, 2, 3, 4, 5])
print("向量", vector)
print("向量的形状", vector.shape)

向量 tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
向量的形状 (5,)


In [38]:
# 创建二维张量（矩阵）
matrix = tf.constant([[1, 2], [3, 4]])
print("矩阵", matrix)
print("矩阵的形状", matrix.shape)
# 创建三维张量
tensor_3d = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print("三维张量", tensor_3d)
print("三维张量形状:", tensor_3d.shape)


矩阵 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
矩阵的形状 (2, 2)
三维张量 tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(1, 3, 3), dtype=int32)
三维张量形状: (1, 3, 3)


In [39]:
# 从numpy数组创建向量
numpy_array = np.array([[1, 2], [3, 4]])
trans_tensor = tf.constant(numpy_array)
print(trans_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [40]:
"""
创建特殊张量
 1. 全零张量
 2. 全一张量
 3. 单位矩阵
 4. 填充张量
 5. 随机张量
"""
# 全零张量
print("全零", tf.zeros([2, 3]))
# 全一张量
print("全一", tf.ones([2, 3]))
# 单位矩阵
print("单位矩阵E", tf.eye(3))
# 填充张量
print("填充张量", tf.fill([2, 2], 9))


全零 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
全一 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
单位矩阵E tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
填充张量 tf.Tensor(
[[9 9]
 [9 9]], shape=(2, 2), dtype=int32)


In [41]:
#随机张量
uniform_tensor = tf.random.uniform([2, 3], minval=0, maxval=1)
print("均匀随机矩阵", uniform_tensor)
# 正态分布
normal_tensor = tf.random.normal([2, 3], mean=0, stddev=1)
print("高斯分布", normal_tensor)

均匀随机矩阵 tf.Tensor(
[[0.7000884  0.74078166 0.29300833]
 [0.29499233 0.03052986 0.6638664 ]], shape=(2, 3), dtype=float32)
高斯分布 tf.Tensor(
[[-0.91589135  0.17096987  0.42432332]
 [ 1.0819371  -1.0404752   1.1664172 ]], shape=(2, 3), dtype=float32)


## 阶段总结
- 张量的创建使用`tf.constant()`方法进行创建，创建方法类似于numpy数组的创建，并且可以将numpy数组转换成tensor
- 注意：使用该方法创建的张量是不可变的

In [42]:
ts1 = tf.constant([[1, 2, 3],
                   [4, 5, 6]], dtype=tf.float32)

print("形状", ts1.shape)
print("张量的维度", ts1.ndim)
print("张量的数据类型", ts1.dtype)
print("元素的数量",tf.size(ts1).numpy())
print("张量存在的设备", ts1.device)

形状 (2, 3)
张量的维度 2
张量的数据类型 <dtype: 'float32'>
元素的数量 6
张量存在的设备 /job:localhost/replica:0/task:0/device:GPU:0


In [43]:
# 数据类型
tensor_f32 = tf.constant([1,2,3], dtype=tf.float32)
tensor_i64 = tf.constant([1,2,3], dtype=tf.int64)
tensor_bool = tf.constant([True, False, True], dtype=tf.bool)
print(tensor_f32.dtype)
print(tensor_i64.dtype)
print(tensor_bool.dtype)

<dtype: 'float32'>
<dtype: 'int64'>
<dtype: 'bool'>


In [45]:
# 数据类型转换
trans_f = tf.cast(tensor_i64, dtype=tf.float32)
print(trans_f.numpy())
print(trans_f.dtype)

[1. 2. 3.]
<dtype: 'float32'>


## 阶段总结
- 张量常用属性分别有：**形状**,**维度**,**类型**,**数量**,**存在的设备**
- 张量常用数据类型为：浮点型、整数型、布尔型，如果想要转换数据类型，使用`cast()`方法，分别传入参数：1. 需要转换的张量 2. 转换的类型