# 张量的操作

In [18]:
import tensorflow as tf

a = tf.constant([[1,2],
                 [3,4]])
b = tf.constant([[5,6],
                [7,8]])

"""

基本运算：
    以下给出两种方法分别进行计算加减乘除
"""
# 方法1:
print("加法", (a + b).numpy())
print("减法", (a - b).numpy())
print("逐元素乘法", (a * b).numpy())
print("逐元素除法", (a / b).numpy())


加法 [[ 6  8]
 [10 12]]
减法 [[-4 -4]
 [-4 -4]]
逐元素乘法 [[ 5 12]
 [21 32]]
逐元素除法 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [19]:
# 方法2：
print("加法",tf.add(a, b))
print("减法", tf.subtract(a, b))
print("逐元素乘法", tf.multiply(a, b))
print("逐元素除法", tf.divide(a, b))

加法 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
减法 tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
逐元素乘法 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
逐元素除法 tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [20]:
# 矩阵乘法
print(tf.matmul(a, b).numpy())

[[19 22]
 [43 50]]


## 阶段总结
- 张量的数学运算有两种运算方式，如果计算两矩阵相乘，则使用`matmul`方法进行计算

In [21]:
"""

矩阵操作

"""
c = tf.constant([[1,2,3],
                 [4,5,6]])
print("原始矩阵",c)
# 改变形状
print("转换为3*2矩阵", tf.reshape(c, [3,2]))

# 展平
print("将矩阵展平", tf.reshape(c, [-1]))

# 矩阵转置
print("转置后的矩阵", tf.transpose(c))


原始矩阵 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
转换为3*2矩阵 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
将矩阵展平 tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
转置后的矩阵 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [31]:
# 增加/减少维度
print("增加维度", tf.expand_dims(c, axis=0)) # 在第0维增加维度
expand_tensor = tf.expand_dims(c, axis=0)
print(expand_tensor)
print("减少维度", tf.squeeze(expand_tensor, axis=0)) # 减少维度

增加维度 tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)
tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)


InvalidArgumentError: {{function_node __wrapped__Squeeze_device_/job:localhost/replica:0/task:0/device:GPU:0}} Can not squeeze dim[1], expected a dimension of 1, got 2 [Op:Squeeze]